version: '3'
services:
  frontend:
    build: .
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8000:8000